services:

  postgres:
    image: postgres:18
    container_name: ledger-postgres

    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger

    ports:
      - "5432:5432"

    volumes:
      - ledger_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d ledger"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    container_name: ledger-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.1.2
    container_name: ledger-kafka

    ports:
      - "9092:9092"


volumes:
  ledger_postgres_data: